fixes #980
selenide/selenide pull request #1289
Opened 2020-10-24 10:09 UTC by eroshenkoam

## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

Posible fixes #980

Action list
- [x] first draft
- [ ] provide tests
- [ ] refactor meta adding

2020-10-24 10:10 UTC, eroshenkoam commented
@asolntsev could you accept my concept

2020-10-24 10:27 UTC, BorisOsipov commented
Be careful
`String url = driver.getWebDriver().getCurrentUrl();`
will throw `UnsupportedCommandException` in appium

2021-01-20 03:25 UTC, Mart-Bogdan requested changes
There is a single bug that makes this code doing nothing.

2021-01-20 03:25 UTC, Mart-Bogdan commented on src/main/java/com/codeborne/selenide/ex/ErrorMessages.java
> +    return screenshot(driver.config(), screenshotPath);
You forgot to add `url` as the second parameter, but the local variable exists.

2021-03-07 10:44 UTC, closed without merging