#1573 - Ability to assert page title
selenide/selenide pull request #1579
Opened 2021-09-23 10:34 UTC by ervuks

## Proposed changes
Implemented feature, requested by https://github.com/selenide/selenide/issues/1573

## Checklist
- [X] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

2021-09-23 16:21 UTC, asolntsev requested changes
1. Isn't it better to rename `title` to `titleContaining` because it check for the substring?
2. Don't we want to have two methods: `title` (for exact match) and `titleContaining` (for substring)?

2021-09-23 18:17 UTC, ervuks commented
Perhaps then just leave the `exact` option without the possibility to check against partial match?

2021-09-23 18:57 UTC, asolntsev commented
@ervuks yes, I like the exact match.

2021-09-24 15:18 UTC, asolntsev approved these changes

2021-09-24 15:30 UTC, merged