feat: added new command to swipe right and left
selenide/selenide pull request #2369
Opened 2023-07-14 07:55 UTC by amuthansakthivel

## Proposed changes
We introduced the scrollTo element in the previous versions and thought the left and right directions were unnecessary. 

But there have been consistent requests to have the option to search for elements by swiping right and left.

I could have added to the existing scroll command but the readability would be awkward. Hence created a new swipe command which is what it needs to be called. 

Sample usage is updated in the readme.md

$(element).swipeTo().click();

## Checklist
- [x] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2023-07-14 09:12 UTC, OleksandrOwl commented on modules/appium/src/main/java/com/codeborne/selenide/appium/commands/SelenideAppiumCommands.java
> +    add("swipe", new AppiumSwipeTo());
Чи потрібно сюди додати ще `add("swipeTo", new AppiumSwipeTo());` ?

2023-07-14 09:21 UTC, amuthansakthivel commented on modules/appium/src/main/java/com/codeborne/selenide/appium/commands/SelenideAppiumCommands.java
> +    add("swipe", new AppiumSwipeTo());
Fixed it. Good catch!

2023-07-19 06:36 UTC, asolntsev requested changes

2023-07-19 06:36 UTC, asolntsev commented on modules/appium/src/main/java/com/codeborne/selenide/appium/commands/SelenideAppiumCommands.java
> +    add("swipe", new AppiumSwipeTo());
@amuthan-sakthivel You added only "swipe" command, but don't you also need to add "swipeTo" command?

2023-07-19 13:45 UTC, amuthansakthivel commented on modules/appium/src/main/java/com/codeborne/selenide/appium/commands/SelenideAppiumCommands.java
> +    add("swipe", new AppiumSwipeTo());
@asolntsev - SwipeTo is already there

![image](https://github.com/selenide/selenide/assets/30618052/74b2b131-62b8-4e8b-8eec-325fedca1e34)

2023-07-22 20:12 UTC, asolntsev approved these changes

2023-07-22 20:18 UTC, asolntsev commented
@amuthansakthivel The build is failing. Can you fix it?

> Task :modules:appium:checkstyleMain
> Error: eckstyle] [ERROR] > AppiumSwipeOptions.java:3:65: Using the '.*' form of import should be avoided - com.codeborne.selenide.appium.AppiumSwipeDirection.*. [AvoidStarImport]

2023-07-23 07:27 UTC, amuthansakthivel commented
Pushed the fix @asolntsev

2023-08-01 21:58 UTC, asolntsev approved these changes

2023-08-01 21:58 UTC, merged