feat: add new selector with className and Index
selenide/selenide pull request #2440
Opened 2023-08-25 15:14 UTC by amuthansakthivel

## Proposed changes
Currently, we do not have a selector which utilises just the class name and index to locate the element

```java
By by = AppiumSelectors.byClassNameAndIndex("android.widget.TextView", 1);
// xpath = (//android.widget.TextView)[1]
```

## Checklist
- [x] Checkstyle and unit tests are passed locally with my changes by running `gradlew check chrome_headless firefox_headless` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2023-08-28 05:39 UTC, asolntsev requested changes
@amuthansakthivel Wait, but it's not correct xpath? No?

For example, `$(byClassNameAndIndex("active", 2))` will generate xpath `"(.//active)[2]"` - but it will NOT find element by class name.

2023-09-12 10:45 UTC, amuthansakthivel commented
> @amuthansakthivel Wait, but it's not correct xpath? No?
> 
> For example, `$(byClassNameAndIndex("active", 2))` will generate xpath `"(.//active)[2]"` - but it will NOT find element by class name.

For mobile, the class name is the tag name

2023-09-12 17:56 UTC, asolntsev approved these changes

2023-09-12 17:57 UTC, merged

2023-09-12 17:57 UTC, asolntsev commented
@amuthansakthivel Ah yes, correct.